### ISSUE TITLE
Problema no uso do docker-compose

### ISSUE THREAD

**Issue by Guilherme-Aguiar** [fga-gpp-mds/2018.1-Grupo9#19]
Fiz a instalação do docker-compose seguindo as instruções do [site](https://docs.docker.com/compose/install/#install-compose), mas quando eu fui tentar criar/iniciar um container houve um erro:

> Can't find a suitable configuration file in this directory or any
>         parent. Are you in the right directory?
> 
>         Supported filenames: docker-compose.yml, docker-compose.yaml
IMAGEM:
![cut](https://user-images.githubusercontent.com/23269406/37315243-6bdc0994-2637-11e8-8f33-ea549d0a440e.png)

**Comment by Eduardojvr** [comment]
Pra rodar tem que entrar na pasta do projeto e depois na pasta leito_hospitalar.

**Comment by Guilherme-Aguiar** [comment]
Como eu acesso a pasta do projeto com a  branch correta?

**Comment by Eduardojvr** [comment]
Já clonou o projeto? Caso não, digite no terminal:  1) git clone https://github.com/fga-gpp-mds/2018.1-Grupo9.git
2) cd 2018.1-Grupo9
3) git checkout docker_configuration
4)docker-compose up

**Comment by Guilherme-Aguiar** [comment]
Segui as instruções mas o problema persiste
IMAGEM:
![cut2](https://user-images.githubusercontent.com/23269406/37316032-aa5fd1b0-263b-11e8-9fdd-0185f9e656f7.png)

**Comment by Eduardojvr** [comment]
Entra na pasta leito_hospitalar

**Comment by Guilherme-Aguiar** [comment]
Ok, mas agora apareceu um novo erro:
IMAGEM:
![captura de tela de 2018-03-12 21-26-35](https://user-images.githubusercontent.com/23269406/37316144-25b4048a-263c-11e8-9afe-b0212313d933.png)

**Comment by Eduardojvr** [comment]
digite: sudo docker-compose up

**Comment by Guilherme-Aguiar** [comment]
Deu certo, vlw!
