### ISSUE TITLE
Erro no Docker 

### ISSUE THREAD

**Issue by drykette** [fga-gpp-mds/2018.1-Grupo9#21]
docker-compose up -d
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by Eduardojvr** [comment]
1) Entre na pasta do projeto;
2) Entre na pasta leito_hospitalar
3) Digite: sudo docker-compose up -d

**Comment by Eduardojvr** [comment]
Nessa issue tem mais detalhes: https://github.com/fga-gpp-mds/2018.1-Grupo9/issues/19
