### ISSUE TITLE
"Couldn't import django" - dificuldade com docker

### ISSUE THREAD

**Issue by Caiocbeleza** [fga-gpp-mds/2018.1-Grupo9#22]
![captura de tela de 2018-03-14 20-41-28](https://user-images.githubusercontent.com/37124720/37436774-67207204-27c8-11e8-9539-701e6d0c298d.png)

Estava tentanto seguir os passos do tutorial django e na hora de criar o app ocorreu esse problema

**Comment by Eduardojvr** [comment]
digite: docker exec -it leitohospitalar_django_1 python manage.py startapp "nome do app"
Esse é o comando para executar o comando de criação de apps dentro do docker!

**Comment by Guilherme-Aguiar** [comment]
agora pra usar o django com o docker eu escrevo na mesmo terminal em que eu iniciei o servidor ou eu abro outro terminal? Pq eu tentei dos dois jeitos e não deu... 

![primeirocaso](https://user-images.githubusercontent.com/23269406/37495913-6e0d6542-288e-11e8-9c78-d1c3bd9cd3f2.png)

![segundocaso](https://user-images.githubusercontent.com/23269406/37495918-72df579c-288e-11e8-8f0f-360b5aa75649.png)

**Comment by Eduardojvr** [comment]
Tente com o sudo!

sudo docker exec -it leitohospitalar_django_1 python manage.py startapp "nome do app"

**Comment by Guilherme-Aguiar** [comment]
Deu! Então sempre que eu for digitar algo de django, como migrate, runserver, startapp, eu só tenho que botar ''sudo docker exec -it leitohospitalar_django_1'' antes né?

**Comment by Eduardojvr** [comment]
Você não precisa fazer isso para "migrate e runserver" porque automatizamos isso, agora para criar app é necessário fazer : sudo docker exec -it leitohospitalar_django_1 python manage.py startapp "nome do app"

**Comment by Eduardojvr** [comment]
Mas se for necessário dar um comando django dentro do container é só fazer: sudo docker -it leitohospitalar_django_1 python manage.py "comando"

**Comment by Eduardojvr** [comment]
Solucionado!
